// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/stock-analyst-layouts/CardGrid.tsx": () => import("../components/mockups/stock-analyst-layouts/CardGrid.tsx"),
  "./components/mockups/stock-analyst-layouts/SplitPane.tsx": () => import("../components/mockups/stock-analyst-layouts/SplitPane.tsx"),
  "./components/mockups/stock-analyst-layouts/TopNav.tsx": () => import("../components/mockups/stock-analyst-layouts/TopNav.tsx")
};
